try{
    alert('welcome')
} catch(error){
    console.log('error');
    

}


